name: Run Git Commands and Build/Test

on:
  push:
    branches:
      - main

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display Git version
        run: git --version

      - name: Install Git and Setup Repository
        run: |
          # INSTALL GIT REPOSITORY

          # Update the Advanced Package Tool
          sudo apt update

          # Install git
          sudo apt install -y git

          # Check git version
          git --version

          # Set account default identity
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

          # SET UP GIT REPOSITORY

          # Create and change to a directory
          mkdir git_project && cd git_project

          # Initialize git in that folder
          git init

          # Create a file
          touch first_file.txt

          # Check git status
          git status

          # Add the file and check the status
          git add first_file.txt
          echo "first file in first branch" >> first_file.txt
          git status

          # Commit the added file
          git commit -m "Initial commit"

          # BRANCH MANAGEMENT

          # Create a branch
          git branch staging

          # Checkout staging branch
          git checkout staging

          # Switch between branches
          git switch master

          # Check the current branch
          git branch

          # Shortcut to create and checkout a new branch
          git checkout -b new_branch

          # Create a file in the branch and commit it
          echo "New file in new branch" >> new_file.txt
          git add .
          git commit -m "Added new file"

          # Merge files from one branch to another
          git merge master
