name: Run Git Commands and Perform Build/Test

on:
  push:
    branches:
      - main

jobs:
  run-git-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Display Git Version
        run: git --version

      - name: Install Git (if not available)
        run: |
          sudo apt update
          sudo apt install -y git

      - name: Run Commands from git_commands.txt
        run: |
          echo "=== Executing Git Commands from git_commands.txt ==="
          mkdir Git_Development_Project
          cd Git_Development_Project

          while IFS= read -r line || [[ -n "$line" ]]; do
            # Skip empty lines and comments
            [[ -z "$line" || "$line" =~ ^# ]] && continue

            echo ">> Running: $line"
            eval "$line"

            if [ $? -ne 0 ]; then
              echo "Command Failed: $line"
              exit 1
            fi
          done < ../git_commands.txt

